version: "3"

services:

  airflow:

    build:
      context: ..
      dockerfile: airflow/Dockerfile

    container_name: tgju-airflow

    ports:
      - "8080:8080"

    volumes:

      - ../dags:/opt/airflow/dags

      - ../src:/opt/airflow/src

      - ../configs:/opt/airflow/configs

      - ../data:/opt/airflow/data

      - ../logs:/opt/airflow/logs

      - ../plugins:/opt/airflow/plugins

    # Allow Docker container to talk to localhost (Hamilton UI) on host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      PYTHONPATH: /opt/airflow
      # Tell the Hamilton SDK where the UI API is located
      HAMILTON_API_URL: http://host.docker.internal:8241
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/data/airflow.db

    command: airflow standalone